# Generated by Django 3.1.1 on 2020-10-11 11:56

from django.db import migrations, models
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('awsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', s3direct.fields.S3DirectField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
